# Clase 02/06
# Introducción R

## entero <- 3
## decimal <- 1.35
## cadena <- "asdffa"
## verdadero <- TRUE
## Falso <- FALSE

```{r}
# Declaración
entero = 5
decimal <- 3.14
cadena = "hola mundo"
verdadero <- TRUE
falso <- F
# Asignación
entero
decimal
cadena
verdadero
falso
```

## Estructuras -> c() ==> c es colección

```{r}
numeros <- c(1, 2, 3, 4, 5)
numeros

letras <- c("a", "b", "c")
letras

logicos <- c(TRUE, FALSE, TRUE)
logicos

mixto <- c(1, "a", FALSE)
mixto
```

## Impresión

```{r}
print(mixto[0]) # character(0)
print(mixto[1]) # 1
print(mixto[2]) # a
print(mixto[3]) # FALSE
```

## Listas

```{r}
mi_lista <- list(numeros = numeros, letras = letras, logicos = logicos)
mi_lista
```

### Acceso a listas

```{r}
mi_lista$numeros
mi_lista$numeros[1]

mi_lista$letras
```

## Matrices
```{r}
matriz <- matrix(1:9, nrow = 3, ncol = 3)
matriz2 <- matrix(c("a", "b", "c"), nrow = 3, ncol = 3)
matriz


matriz[1] # 1
matriz[1,] # 1 4 7
matriz[1,3] # 7
matriz[,2] # 4 5 6
```

## Dataframes
```{r}
data_frame <- data.frame(
  nombre = c("Ana", "Luis", "Pedro"),
  edad = c(22, 23, 25),
  aprobado = c(TRUE, FALSE, TRUE)
)
data_frame

data_frame$nombre[1] # Ana
data_frame$nombre[2] # Luis

data_frame$nombre # Ana Luis Pedro
```

## Factor (tambien se le conoce como distinc)
```{r}
colores <- factor(c("rojo", "azul", "verde", "rojo", "azul", "amarillo", "rosa"))
print(colores) # poder sacar un valor

levels(colores) # agarrar los valores poner los únicos
```

## Funciones
```{r}
funcion <- function(x, y) {
  resultado <- x + y
  return(resultado)
}

funcion(20, 5) # En caso de poner numéricos en "" hay que castear de suma y números no pueden ser de forma implícita
```

## Concatenación
```{r}
a = 10
b = TRUE
res = a - b
res

### Concatenar valores
a = 10
b = "a"
paste(b, b, sep = "-") # a-a
paste(a, b, sep = "-") # 10-a
paste(a, b, sep = "") # 10a
```

## Colecciones
```{r}
arrl = c(10, 20, 30, 40, 50)
arrl = c(arrl, 60, 70, 80, 90)
arrl # 10, 20, 30, 40, 50, 60, 70, 80, 90

# Ingreso
arrl[-1] # 20, 30, 40, 50, 60, 70, 80, 90

# Otra forma
arrl[c(-1, -3, -7)] # 20, 40, 50, 60, 80, 90
```

## Costos
```{r}
# set.seed(1234)
#           uniforme  100 aleatorios, minimo de 10 y máx de 50
arr.costo = runif(100, min = 10, max = 50) # Distribuciones
arr.costo
sum(arr.costo)
```

```{r}
arr.costo[20]
```

```{r}
arr.costo > 30
```


```{r}
sum(arr.costo > 30)
sum(arr.costo <= 30)
```

```{r}
arr.costo[arr.costo <= 30]
sum(arr.costo) # Sumar costos
which.max(arr.costo) # manda valores, dice cual es el valor máx (indice)
which.min(arr.costo) # manda valores, dice cual es el valor máx
```

## Divisiones
```{r}
probA = 10/50
probA
```

## Listas
```{r}
lista = list(32, "hola", c(25,10,35), c(T,F,F,T,T,F,F), TRUE)
lista

listaBool = lista[4]
listaBool[[1]][4] ## [[indice]][posición]
```

```{r}
lista[[2]]
lista[[3]][2]
```

```{r}
datos <- list(
  nombre = 'Daniel',
  apellido = 'Vega',
  edad = 30,
  clases = c("SO2", "SEMI1", "DB2")
)
datos
```

```{r}
datos$nombre
datos$clases[3]
```

# Clase 03/06

```{r}
n_alumnos <- 1000
notas <- as.integer(runif(n_alumnos, min = 71, max = 100))
secciones_activas <- c('A', 'B', 'U', 'V')
secciones <- sample(secciones_activas, n_alumnos, replace = TRUE)

ids <- as.integer(runif(n_alumnos, min = 1000, max = 9999)) # generar distribución uniforme
anio <- sample(c(2015, 2016, 2017, 2018), n_alumnos, replace = TRUE)
carnets <- paste(anio, ids, sep = "")
alumnos <- list(carnet = carnets, seccion = secciones, nota = notas)

## Ver alumnos
View(alumnos)
```

## Análisis exploratorio
```{r}
# Ver cantidad de carnets para la sección A
length(alumnos$carnet[alumnos$seccion == "A"])

# Promedio alumnos año 2017
mean(alumnos$nota[substr(alumnos$carnet, 1, 4) == '2017'])
```

```{r}
n <- 100
dataset <- data.frame(
  cantidad = as.integer(runif(n, min = 10, max = 100)),
  precio = rnorm(n, mean = 50, sd = 25),
  disponible = sample(c(T,F), n, replace = T)
)
dataset

nrow(dataset)
ncol(dataset)
dim(dataset)
colnames(dataset)
```

```{r}
colnames(dataset) <- c("Cantidad", "Precio", "Disponible")

dataset[,1]

dataset[, c(1,3)]

dataset[1,]

dataset[c(1, 10, 100),]

dataset[c(1, 10, 100), c(2,3)] # aqui el c(2,3) sería en donde aparece la columna 2 y 3 (orden)
```

```{r}
# Filtrar
dataset[dataset$Disponible == T,] # quiero donde disponible sea True

dataset[dataset$Disponible == T,c(1)] # quiero donde disponible sea True
```

```{r}
filtro <- ((dataset$Disponible == T) & (dataset$Precio <= 50)) #Agarra el dataset disponible y con precion <= a 50
dataset[filtro,] # Se puede colocar una columna específica en orden
```

```{r}
mean(dataset$Precio)
```

```{r}
# Importación de librerías
library(nycflights23)
library(dplyr)
library(ggplot2)
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```


















